
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.7.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace LC.Model.BMS.DAL
{
	public abstract class _tblFaxes : SqlClientEntity
	{
		public _tblFaxes()
		{
			this.QuerySource = "tblFaxes";
			this.MappingName = "tblFaxes";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblFaxesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int PkFaxID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.PkFaxID, PkFaxID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblFaxesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter PkFaxID
			{
				get
				{
					return new SqlParameter("@PkFaxID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter FTitle
			{
				get
				{
					return new SqlParameter("@FTitle", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter FSendEmail
			{
				get
				{
					return new SqlParameter("@FSendEmail", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter FOwnEmail
			{
				get
				{
					return new SqlParameter("@FOwnEmail", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter FSendingMailLoginUser
			{
				get
				{
					return new SqlParameter("@FSendingMailLoginUser", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter FSendingMailLoginPassword
			{
				get
				{
					return new SqlParameter("@FSendingMailLoginPassword", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter DModifiedDate
			{
				get
				{
					return new SqlParameter("@DModifiedDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter DCreatedDate
			{
				get
				{
					return new SqlParameter("@DCreatedDate", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string PkFaxID = "pkFaxID";
            public const string FTitle = "fTitle";
            public const string FSendEmail = "fSendEmail";
            public const string FOwnEmail = "fOwnEmail";
            public const string FSendingMailLoginUser = "fSendingMailLoginUser";
            public const string FSendingMailLoginPassword = "fSendingMailLoginPassword";
            public const string DModifiedDate = "dModifiedDate";
            public const string DCreatedDate = "dCreatedDate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PkFaxID] = _tblFaxes.PropertyNames.PkFaxID;
					ht[FTitle] = _tblFaxes.PropertyNames.FTitle;
					ht[FSendEmail] = _tblFaxes.PropertyNames.FSendEmail;
					ht[FOwnEmail] = _tblFaxes.PropertyNames.FOwnEmail;
					ht[FSendingMailLoginUser] = _tblFaxes.PropertyNames.FSendingMailLoginUser;
					ht[FSendingMailLoginPassword] = _tblFaxes.PropertyNames.FSendingMailLoginPassword;
					ht[DModifiedDate] = _tblFaxes.PropertyNames.DModifiedDate;
					ht[DCreatedDate] = _tblFaxes.PropertyNames.DCreatedDate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string PkFaxID = "PkFaxID";
            public const string FTitle = "FTitle";
            public const string FSendEmail = "FSendEmail";
            public const string FOwnEmail = "FOwnEmail";
            public const string FSendingMailLoginUser = "FSendingMailLoginUser";
            public const string FSendingMailLoginPassword = "FSendingMailLoginPassword";
            public const string DModifiedDate = "DModifiedDate";
            public const string DCreatedDate = "DCreatedDate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PkFaxID] = _tblFaxes.ColumnNames.PkFaxID;
					ht[FTitle] = _tblFaxes.ColumnNames.FTitle;
					ht[FSendEmail] = _tblFaxes.ColumnNames.FSendEmail;
					ht[FOwnEmail] = _tblFaxes.ColumnNames.FOwnEmail;
					ht[FSendingMailLoginUser] = _tblFaxes.ColumnNames.FSendingMailLoginUser;
					ht[FSendingMailLoginPassword] = _tblFaxes.ColumnNames.FSendingMailLoginPassword;
					ht[DModifiedDate] = _tblFaxes.ColumnNames.DModifiedDate;
					ht[DCreatedDate] = _tblFaxes.ColumnNames.DCreatedDate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string PkFaxID = "s_PkFaxID";
            public const string FTitle = "s_FTitle";
            public const string FSendEmail = "s_FSendEmail";
            public const string FOwnEmail = "s_FOwnEmail";
            public const string FSendingMailLoginUser = "s_FSendingMailLoginUser";
            public const string FSendingMailLoginPassword = "s_FSendingMailLoginPassword";
            public const string DModifiedDate = "s_DModifiedDate";
            public const string DCreatedDate = "s_DCreatedDate";

		}
		#endregion		
		
		#region Properties
	
		public virtual int PkFaxID
	    {
			get
	        {
				return base.Getint(ColumnNames.PkFaxID);
			}
			set
	        {
				base.Setint(ColumnNames.PkFaxID, value);
			}
		}

		public virtual string FTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.FTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.FTitle, value);
			}
		}

		public virtual string FSendEmail
	    {
			get
	        {
				return base.Getstring(ColumnNames.FSendEmail);
			}
			set
	        {
				base.Setstring(ColumnNames.FSendEmail, value);
			}
		}

		public virtual string FOwnEmail
	    {
			get
	        {
				return base.Getstring(ColumnNames.FOwnEmail);
			}
			set
	        {
				base.Setstring(ColumnNames.FOwnEmail, value);
			}
		}

		public virtual string FSendingMailLoginUser
	    {
			get
	        {
				return base.Getstring(ColumnNames.FSendingMailLoginUser);
			}
			set
	        {
				base.Setstring(ColumnNames.FSendingMailLoginUser, value);
			}
		}

		public virtual string FSendingMailLoginPassword
	    {
			get
	        {
				return base.Getstring(ColumnNames.FSendingMailLoginPassword);
			}
			set
	        {
				base.Setstring(ColumnNames.FSendingMailLoginPassword, value);
			}
		}

		public virtual DateTime DModifiedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.DModifiedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.DModifiedDate, value);
			}
		}

		public virtual DateTime DCreatedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.DCreatedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.DCreatedDate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_PkFaxID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PkFaxID) ? string.Empty : base.GetintAsString(ColumnNames.PkFaxID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PkFaxID);
				else
					this.PkFaxID = base.SetintAsString(ColumnNames.PkFaxID, value);
			}
		}

		public virtual string s_FTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FTitle) ? string.Empty : base.GetstringAsString(ColumnNames.FTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FTitle);
				else
					this.FTitle = base.SetstringAsString(ColumnNames.FTitle, value);
			}
		}

		public virtual string s_FSendEmail
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FSendEmail) ? string.Empty : base.GetstringAsString(ColumnNames.FSendEmail);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FSendEmail);
				else
					this.FSendEmail = base.SetstringAsString(ColumnNames.FSendEmail, value);
			}
		}

		public virtual string s_FOwnEmail
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FOwnEmail) ? string.Empty : base.GetstringAsString(ColumnNames.FOwnEmail);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FOwnEmail);
				else
					this.FOwnEmail = base.SetstringAsString(ColumnNames.FOwnEmail, value);
			}
		}

		public virtual string s_FSendingMailLoginUser
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FSendingMailLoginUser) ? string.Empty : base.GetstringAsString(ColumnNames.FSendingMailLoginUser);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FSendingMailLoginUser);
				else
					this.FSendingMailLoginUser = base.SetstringAsString(ColumnNames.FSendingMailLoginUser, value);
			}
		}

		public virtual string s_FSendingMailLoginPassword
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FSendingMailLoginPassword) ? string.Empty : base.GetstringAsString(ColumnNames.FSendingMailLoginPassword);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FSendingMailLoginPassword);
				else
					this.FSendingMailLoginPassword = base.SetstringAsString(ColumnNames.FSendingMailLoginPassword, value);
			}
		}

		public virtual string s_DModifiedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DModifiedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.DModifiedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DModifiedDate);
				else
					this.DModifiedDate = base.SetDateTimeAsString(ColumnNames.DModifiedDate, value);
			}
		}

		public virtual string s_DCreatedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DCreatedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.DCreatedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DCreatedDate);
				else
					this.DCreatedDate = base.SetDateTimeAsString(ColumnNames.DCreatedDate, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter PkFaxID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PkFaxID, Parameters.PkFaxID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FTitle, Parameters.FTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FSendEmail
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FSendEmail, Parameters.FSendEmail);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FOwnEmail
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FOwnEmail, Parameters.FOwnEmail);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FSendingMailLoginUser
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FSendingMailLoginUser, Parameters.FSendingMailLoginUser);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FSendingMailLoginPassword
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FSendingMailLoginPassword, Parameters.FSendingMailLoginPassword);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DModifiedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DModifiedDate, Parameters.DModifiedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DCreatedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DCreatedDate, Parameters.DCreatedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter PkFaxID
		    {
				get
		        {
					if(_PkFaxID_W == null)
	        	    {
						_PkFaxID_W = TearOff.PkFaxID;
					}
					return _PkFaxID_W;
				}
			}

			public WhereParameter FTitle
		    {
				get
		        {
					if(_FTitle_W == null)
	        	    {
						_FTitle_W = TearOff.FTitle;
					}
					return _FTitle_W;
				}
			}

			public WhereParameter FSendEmail
		    {
				get
		        {
					if(_FSendEmail_W == null)
	        	    {
						_FSendEmail_W = TearOff.FSendEmail;
					}
					return _FSendEmail_W;
				}
			}

			public WhereParameter FOwnEmail
		    {
				get
		        {
					if(_FOwnEmail_W == null)
	        	    {
						_FOwnEmail_W = TearOff.FOwnEmail;
					}
					return _FOwnEmail_W;
				}
			}

			public WhereParameter FSendingMailLoginUser
		    {
				get
		        {
					if(_FSendingMailLoginUser_W == null)
	        	    {
						_FSendingMailLoginUser_W = TearOff.FSendingMailLoginUser;
					}
					return _FSendingMailLoginUser_W;
				}
			}

			public WhereParameter FSendingMailLoginPassword
		    {
				get
		        {
					if(_FSendingMailLoginPassword_W == null)
	        	    {
						_FSendingMailLoginPassword_W = TearOff.FSendingMailLoginPassword;
					}
					return _FSendingMailLoginPassword_W;
				}
			}

			public WhereParameter DModifiedDate
		    {
				get
		        {
					if(_DModifiedDate_W == null)
	        	    {
						_DModifiedDate_W = TearOff.DModifiedDate;
					}
					return _DModifiedDate_W;
				}
			}

			public WhereParameter DCreatedDate
		    {
				get
		        {
					if(_DCreatedDate_W == null)
	        	    {
						_DCreatedDate_W = TearOff.DCreatedDate;
					}
					return _DCreatedDate_W;
				}
			}

			private WhereParameter _PkFaxID_W = null;
			private WhereParameter _FTitle_W = null;
			private WhereParameter _FSendEmail_W = null;
			private WhereParameter _FOwnEmail_W = null;
			private WhereParameter _FSendingMailLoginUser_W = null;
			private WhereParameter _FSendingMailLoginPassword_W = null;
			private WhereParameter _DModifiedDate_W = null;
			private WhereParameter _DCreatedDate_W = null;

			public void WhereClauseReset()
			{
				_PkFaxID_W = null;
				_FTitle_W = null;
				_FSendEmail_W = null;
				_FOwnEmail_W = null;
				_FSendingMailLoginUser_W = null;
				_FSendingMailLoginPassword_W = null;
				_DModifiedDate_W = null;
				_DCreatedDate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter PkFaxID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PkFaxID, Parameters.PkFaxID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FTitle, Parameters.FTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FSendEmail
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FSendEmail, Parameters.FSendEmail);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FOwnEmail
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FOwnEmail, Parameters.FOwnEmail);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FSendingMailLoginUser
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FSendingMailLoginUser, Parameters.FSendingMailLoginUser);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FSendingMailLoginPassword
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FSendingMailLoginPassword, Parameters.FSendingMailLoginPassword);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DModifiedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DModifiedDate, Parameters.DModifiedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DCreatedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DCreatedDate, Parameters.DCreatedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter PkFaxID
		    {
				get
		        {
					if(_PkFaxID_W == null)
	        	    {
						_PkFaxID_W = TearOff.PkFaxID;
					}
					return _PkFaxID_W;
				}
			}

			public AggregateParameter FTitle
		    {
				get
		        {
					if(_FTitle_W == null)
	        	    {
						_FTitle_W = TearOff.FTitle;
					}
					return _FTitle_W;
				}
			}

			public AggregateParameter FSendEmail
		    {
				get
		        {
					if(_FSendEmail_W == null)
	        	    {
						_FSendEmail_W = TearOff.FSendEmail;
					}
					return _FSendEmail_W;
				}
			}

			public AggregateParameter FOwnEmail
		    {
				get
		        {
					if(_FOwnEmail_W == null)
	        	    {
						_FOwnEmail_W = TearOff.FOwnEmail;
					}
					return _FOwnEmail_W;
				}
			}

			public AggregateParameter FSendingMailLoginUser
		    {
				get
		        {
					if(_FSendingMailLoginUser_W == null)
	        	    {
						_FSendingMailLoginUser_W = TearOff.FSendingMailLoginUser;
					}
					return _FSendingMailLoginUser_W;
				}
			}

			public AggregateParameter FSendingMailLoginPassword
		    {
				get
		        {
					if(_FSendingMailLoginPassword_W == null)
	        	    {
						_FSendingMailLoginPassword_W = TearOff.FSendingMailLoginPassword;
					}
					return _FSendingMailLoginPassword_W;
				}
			}

			public AggregateParameter DModifiedDate
		    {
				get
		        {
					if(_DModifiedDate_W == null)
	        	    {
						_DModifiedDate_W = TearOff.DModifiedDate;
					}
					return _DModifiedDate_W;
				}
			}

			public AggregateParameter DCreatedDate
		    {
				get
		        {
					if(_DCreatedDate_W == null)
	        	    {
						_DCreatedDate_W = TearOff.DCreatedDate;
					}
					return _DCreatedDate_W;
				}
			}

			private AggregateParameter _PkFaxID_W = null;
			private AggregateParameter _FTitle_W = null;
			private AggregateParameter _FSendEmail_W = null;
			private AggregateParameter _FOwnEmail_W = null;
			private AggregateParameter _FSendingMailLoginUser_W = null;
			private AggregateParameter _FSendingMailLoginPassword_W = null;
			private AggregateParameter _DModifiedDate_W = null;
			private AggregateParameter _DCreatedDate_W = null;

			public void AggregateClauseReset()
			{
				_PkFaxID_W = null;
				_FTitle_W = null;
				_FSendEmail_W = null;
				_FOwnEmail_W = null;
				_FSendingMailLoginUser_W = null;
				_FSendingMailLoginPassword_W = null;
				_DModifiedDate_W = null;
				_DCreatedDate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblFaxesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.PkFaxID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblFaxesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblFaxesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.PkFaxID);
			p.SourceColumn = ColumnNames.PkFaxID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.PkFaxID);
			p.SourceColumn = ColumnNames.PkFaxID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FTitle);
			p.SourceColumn = ColumnNames.FTitle;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FSendEmail);
			p.SourceColumn = ColumnNames.FSendEmail;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FOwnEmail);
			p.SourceColumn = ColumnNames.FOwnEmail;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FSendingMailLoginUser);
			p.SourceColumn = ColumnNames.FSendingMailLoginUser;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FSendingMailLoginPassword);
			p.SourceColumn = ColumnNames.FSendingMailLoginPassword;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DModifiedDate);
			p.SourceColumn = ColumnNames.DModifiedDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DCreatedDate);
			p.SourceColumn = ColumnNames.DCreatedDate;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
