
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.7.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace LC.Model.BMS.DAL
{
	public abstract class _tblSalaryTypes : SqlClientEntity
	{
		public _tblSalaryTypes()
		{
			this.QuerySource = "tblSalaryTypes";
			this.MappingName = "tblSalaryTypes";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblSalaryTypesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int PkSalaryTypeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.PkSalaryTypeID, PkSalaryTypeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblSalaryTypesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter PkSalaryTypeID
			{
				get
				{
					return new SqlParameter("@PkSalaryTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter SSalaryType
			{
				get
				{
					return new SqlParameter("@SSalaryType", SqlDbType.NVarChar, 50);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string PkSalaryTypeID = "pkSalaryTypeID";
            public const string SSalaryType = "sSalaryType";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PkSalaryTypeID] = _tblSalaryTypes.PropertyNames.PkSalaryTypeID;
					ht[SSalaryType] = _tblSalaryTypes.PropertyNames.SSalaryType;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string PkSalaryTypeID = "PkSalaryTypeID";
            public const string SSalaryType = "SSalaryType";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PkSalaryTypeID] = _tblSalaryTypes.ColumnNames.PkSalaryTypeID;
					ht[SSalaryType] = _tblSalaryTypes.ColumnNames.SSalaryType;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string PkSalaryTypeID = "s_PkSalaryTypeID";
            public const string SSalaryType = "s_SSalaryType";

		}
		#endregion		
		
		#region Properties
	
		public virtual int PkSalaryTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.PkSalaryTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.PkSalaryTypeID, value);
			}
		}

		public virtual string SSalaryType
	    {
			get
	        {
				return base.Getstring(ColumnNames.SSalaryType);
			}
			set
	        {
				base.Setstring(ColumnNames.SSalaryType, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_PkSalaryTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PkSalaryTypeID) ? string.Empty : base.GetintAsString(ColumnNames.PkSalaryTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PkSalaryTypeID);
				else
					this.PkSalaryTypeID = base.SetintAsString(ColumnNames.PkSalaryTypeID, value);
			}
		}

		public virtual string s_SSalaryType
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SSalaryType) ? string.Empty : base.GetstringAsString(ColumnNames.SSalaryType);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SSalaryType);
				else
					this.SSalaryType = base.SetstringAsString(ColumnNames.SSalaryType, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter PkSalaryTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PkSalaryTypeID, Parameters.PkSalaryTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SSalaryType
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SSalaryType, Parameters.SSalaryType);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter PkSalaryTypeID
		    {
				get
		        {
					if(_PkSalaryTypeID_W == null)
	        	    {
						_PkSalaryTypeID_W = TearOff.PkSalaryTypeID;
					}
					return _PkSalaryTypeID_W;
				}
			}

			public WhereParameter SSalaryType
		    {
				get
		        {
					if(_SSalaryType_W == null)
	        	    {
						_SSalaryType_W = TearOff.SSalaryType;
					}
					return _SSalaryType_W;
				}
			}

			private WhereParameter _PkSalaryTypeID_W = null;
			private WhereParameter _SSalaryType_W = null;

			public void WhereClauseReset()
			{
				_PkSalaryTypeID_W = null;
				_SSalaryType_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter PkSalaryTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PkSalaryTypeID, Parameters.PkSalaryTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SSalaryType
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SSalaryType, Parameters.SSalaryType);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter PkSalaryTypeID
		    {
				get
		        {
					if(_PkSalaryTypeID_W == null)
	        	    {
						_PkSalaryTypeID_W = TearOff.PkSalaryTypeID;
					}
					return _PkSalaryTypeID_W;
				}
			}

			public AggregateParameter SSalaryType
		    {
				get
		        {
					if(_SSalaryType_W == null)
	        	    {
						_SSalaryType_W = TearOff.SSalaryType;
					}
					return _SSalaryType_W;
				}
			}

			private AggregateParameter _PkSalaryTypeID_W = null;
			private AggregateParameter _SSalaryType_W = null;

			public void AggregateClauseReset()
			{
				_PkSalaryTypeID_W = null;
				_SSalaryType_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblSalaryTypesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.PkSalaryTypeID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblSalaryTypesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblSalaryTypesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.PkSalaryTypeID);
			p.SourceColumn = ColumnNames.PkSalaryTypeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.PkSalaryTypeID);
			p.SourceColumn = ColumnNames.PkSalaryTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.SSalaryType);
			p.SourceColumn = ColumnNames.SSalaryType;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
