
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.7.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace LC.Model.BMS.DAL
{
	public abstract class _tblRegisters : SqlClientEntity
	{
		public _tblRegisters()
		{
			this.QuerySource = "tblRegisters";
			this.MappingName = "tblRegisters";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblRegistersLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int PkRegisterID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.PkRegisterID, PkRegisterID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblRegistersLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter PkRegisterID
			{
				get
				{
					return new SqlParameter("@PkRegisterID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter RName
			{
				get
				{
					return new SqlParameter("@RName", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter RDescription
			{
				get
				{
					return new SqlParameter("@RDescription", SqlDbType.NText, 1073741823);
				}
			}
			
			public static SqlParameter FkVatID
			{
				get
				{
					return new SqlParameter("@FkVatID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter RComment
			{
				get
				{
					return new SqlParameter("@RComment", SqlDbType.NText, 1073741823);
				}
			}
			
			public static SqlParameter IsActive
			{
				get
				{
					return new SqlParameter("@IsActive", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter DCreatedDate
			{
				get
				{
					return new SqlParameter("@DCreatedDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter DModifiedDate
			{
				get
				{
					return new SqlParameter("@DModifiedDate", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string PkRegisterID = "pkRegisterID";
            public const string RName = "rName";
            public const string RDescription = "rDescription";
            public const string FkVatID = "fkVatID";
            public const string RComment = "rComment";
            public const string IsActive = "isActive";
            public const string DCreatedDate = "dCreatedDate";
            public const string DModifiedDate = "dModifiedDate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PkRegisterID] = _tblRegisters.PropertyNames.PkRegisterID;
					ht[RName] = _tblRegisters.PropertyNames.RName;
					ht[RDescription] = _tblRegisters.PropertyNames.RDescription;
					ht[FkVatID] = _tblRegisters.PropertyNames.FkVatID;
					ht[RComment] = _tblRegisters.PropertyNames.RComment;
					ht[IsActive] = _tblRegisters.PropertyNames.IsActive;
					ht[DCreatedDate] = _tblRegisters.PropertyNames.DCreatedDate;
					ht[DModifiedDate] = _tblRegisters.PropertyNames.DModifiedDate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string PkRegisterID = "PkRegisterID";
            public const string RName = "RName";
            public const string RDescription = "RDescription";
            public const string FkVatID = "FkVatID";
            public const string RComment = "RComment";
            public const string IsActive = "IsActive";
            public const string DCreatedDate = "DCreatedDate";
            public const string DModifiedDate = "DModifiedDate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[PkRegisterID] = _tblRegisters.ColumnNames.PkRegisterID;
					ht[RName] = _tblRegisters.ColumnNames.RName;
					ht[RDescription] = _tblRegisters.ColumnNames.RDescription;
					ht[FkVatID] = _tblRegisters.ColumnNames.FkVatID;
					ht[RComment] = _tblRegisters.ColumnNames.RComment;
					ht[IsActive] = _tblRegisters.ColumnNames.IsActive;
					ht[DCreatedDate] = _tblRegisters.ColumnNames.DCreatedDate;
					ht[DModifiedDate] = _tblRegisters.ColumnNames.DModifiedDate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string PkRegisterID = "s_PkRegisterID";
            public const string RName = "s_RName";
            public const string RDescription = "s_RDescription";
            public const string FkVatID = "s_FkVatID";
            public const string RComment = "s_RComment";
            public const string IsActive = "s_IsActive";
            public const string DCreatedDate = "s_DCreatedDate";
            public const string DModifiedDate = "s_DModifiedDate";

		}
		#endregion		
		
		#region Properties
	
		public virtual int PkRegisterID
	    {
			get
	        {
				return base.Getint(ColumnNames.PkRegisterID);
			}
			set
	        {
				base.Setint(ColumnNames.PkRegisterID, value);
			}
		}

		public virtual string RName
	    {
			get
	        {
				return base.Getstring(ColumnNames.RName);
			}
			set
	        {
				base.Setstring(ColumnNames.RName, value);
			}
		}

		public virtual string RDescription
	    {
			get
	        {
				return base.Getstring(ColumnNames.RDescription);
			}
			set
	        {
				base.Setstring(ColumnNames.RDescription, value);
			}
		}

		public virtual int FkVatID
	    {
			get
	        {
				return base.Getint(ColumnNames.FkVatID);
			}
			set
	        {
				base.Setint(ColumnNames.FkVatID, value);
			}
		}

		public virtual string RComment
	    {
			get
	        {
				return base.Getstring(ColumnNames.RComment);
			}
			set
	        {
				base.Setstring(ColumnNames.RComment, value);
			}
		}

		public virtual bool IsActive
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsActive);
			}
			set
	        {
				base.Setbool(ColumnNames.IsActive, value);
			}
		}

		public virtual DateTime DCreatedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.DCreatedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.DCreatedDate, value);
			}
		}

		public virtual DateTime DModifiedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.DModifiedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.DModifiedDate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_PkRegisterID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PkRegisterID) ? string.Empty : base.GetintAsString(ColumnNames.PkRegisterID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PkRegisterID);
				else
					this.PkRegisterID = base.SetintAsString(ColumnNames.PkRegisterID, value);
			}
		}

		public virtual string s_RName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RName) ? string.Empty : base.GetstringAsString(ColumnNames.RName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RName);
				else
					this.RName = base.SetstringAsString(ColumnNames.RName, value);
			}
		}

		public virtual string s_RDescription
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RDescription) ? string.Empty : base.GetstringAsString(ColumnNames.RDescription);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RDescription);
				else
					this.RDescription = base.SetstringAsString(ColumnNames.RDescription, value);
			}
		}

		public virtual string s_FkVatID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FkVatID) ? string.Empty : base.GetintAsString(ColumnNames.FkVatID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FkVatID);
				else
					this.FkVatID = base.SetintAsString(ColumnNames.FkVatID, value);
			}
		}

		public virtual string s_RComment
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RComment) ? string.Empty : base.GetstringAsString(ColumnNames.RComment);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RComment);
				else
					this.RComment = base.SetstringAsString(ColumnNames.RComment, value);
			}
		}

		public virtual string s_IsActive
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsActive) ? string.Empty : base.GetboolAsString(ColumnNames.IsActive);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsActive);
				else
					this.IsActive = base.SetboolAsString(ColumnNames.IsActive, value);
			}
		}

		public virtual string s_DCreatedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DCreatedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.DCreatedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DCreatedDate);
				else
					this.DCreatedDate = base.SetDateTimeAsString(ColumnNames.DCreatedDate, value);
			}
		}

		public virtual string s_DModifiedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DModifiedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.DModifiedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DModifiedDate);
				else
					this.DModifiedDate = base.SetDateTimeAsString(ColumnNames.DModifiedDate, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter PkRegisterID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PkRegisterID, Parameters.PkRegisterID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RName, Parameters.RName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RDescription
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RDescription, Parameters.RDescription);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FkVatID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FkVatID, Parameters.FkVatID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RComment
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RComment, Parameters.RComment);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsActive
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsActive, Parameters.IsActive);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DCreatedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DCreatedDate, Parameters.DCreatedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DModifiedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DModifiedDate, Parameters.DModifiedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter PkRegisterID
		    {
				get
		        {
					if(_PkRegisterID_W == null)
	        	    {
						_PkRegisterID_W = TearOff.PkRegisterID;
					}
					return _PkRegisterID_W;
				}
			}

			public WhereParameter RName
		    {
				get
		        {
					if(_RName_W == null)
	        	    {
						_RName_W = TearOff.RName;
					}
					return _RName_W;
				}
			}

			public WhereParameter RDescription
		    {
				get
		        {
					if(_RDescription_W == null)
	        	    {
						_RDescription_W = TearOff.RDescription;
					}
					return _RDescription_W;
				}
			}

			public WhereParameter FkVatID
		    {
				get
		        {
					if(_FkVatID_W == null)
	        	    {
						_FkVatID_W = TearOff.FkVatID;
					}
					return _FkVatID_W;
				}
			}

			public WhereParameter RComment
		    {
				get
		        {
					if(_RComment_W == null)
	        	    {
						_RComment_W = TearOff.RComment;
					}
					return _RComment_W;
				}
			}

			public WhereParameter IsActive
		    {
				get
		        {
					if(_IsActive_W == null)
	        	    {
						_IsActive_W = TearOff.IsActive;
					}
					return _IsActive_W;
				}
			}

			public WhereParameter DCreatedDate
		    {
				get
		        {
					if(_DCreatedDate_W == null)
	        	    {
						_DCreatedDate_W = TearOff.DCreatedDate;
					}
					return _DCreatedDate_W;
				}
			}

			public WhereParameter DModifiedDate
		    {
				get
		        {
					if(_DModifiedDate_W == null)
	        	    {
						_DModifiedDate_W = TearOff.DModifiedDate;
					}
					return _DModifiedDate_W;
				}
			}

			private WhereParameter _PkRegisterID_W = null;
			private WhereParameter _RName_W = null;
			private WhereParameter _RDescription_W = null;
			private WhereParameter _FkVatID_W = null;
			private WhereParameter _RComment_W = null;
			private WhereParameter _IsActive_W = null;
			private WhereParameter _DCreatedDate_W = null;
			private WhereParameter _DModifiedDate_W = null;

			public void WhereClauseReset()
			{
				_PkRegisterID_W = null;
				_RName_W = null;
				_RDescription_W = null;
				_FkVatID_W = null;
				_RComment_W = null;
				_IsActive_W = null;
				_DCreatedDate_W = null;
				_DModifiedDate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter PkRegisterID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PkRegisterID, Parameters.PkRegisterID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RName, Parameters.RName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RDescription
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RDescription, Parameters.RDescription);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FkVatID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FkVatID, Parameters.FkVatID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RComment
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RComment, Parameters.RComment);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsActive
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsActive, Parameters.IsActive);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DCreatedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DCreatedDate, Parameters.DCreatedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DModifiedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DModifiedDate, Parameters.DModifiedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter PkRegisterID
		    {
				get
		        {
					if(_PkRegisterID_W == null)
	        	    {
						_PkRegisterID_W = TearOff.PkRegisterID;
					}
					return _PkRegisterID_W;
				}
			}

			public AggregateParameter RName
		    {
				get
		        {
					if(_RName_W == null)
	        	    {
						_RName_W = TearOff.RName;
					}
					return _RName_W;
				}
			}

			public AggregateParameter RDescription
		    {
				get
		        {
					if(_RDescription_W == null)
	        	    {
						_RDescription_W = TearOff.RDescription;
					}
					return _RDescription_W;
				}
			}

			public AggregateParameter FkVatID
		    {
				get
		        {
					if(_FkVatID_W == null)
	        	    {
						_FkVatID_W = TearOff.FkVatID;
					}
					return _FkVatID_W;
				}
			}

			public AggregateParameter RComment
		    {
				get
		        {
					if(_RComment_W == null)
	        	    {
						_RComment_W = TearOff.RComment;
					}
					return _RComment_W;
				}
			}

			public AggregateParameter IsActive
		    {
				get
		        {
					if(_IsActive_W == null)
	        	    {
						_IsActive_W = TearOff.IsActive;
					}
					return _IsActive_W;
				}
			}

			public AggregateParameter DCreatedDate
		    {
				get
		        {
					if(_DCreatedDate_W == null)
	        	    {
						_DCreatedDate_W = TearOff.DCreatedDate;
					}
					return _DCreatedDate_W;
				}
			}

			public AggregateParameter DModifiedDate
		    {
				get
		        {
					if(_DModifiedDate_W == null)
	        	    {
						_DModifiedDate_W = TearOff.DModifiedDate;
					}
					return _DModifiedDate_W;
				}
			}

			private AggregateParameter _PkRegisterID_W = null;
			private AggregateParameter _RName_W = null;
			private AggregateParameter _RDescription_W = null;
			private AggregateParameter _FkVatID_W = null;
			private AggregateParameter _RComment_W = null;
			private AggregateParameter _IsActive_W = null;
			private AggregateParameter _DCreatedDate_W = null;
			private AggregateParameter _DModifiedDate_W = null;

			public void AggregateClauseReset()
			{
				_PkRegisterID_W = null;
				_RName_W = null;
				_RDescription_W = null;
				_FkVatID_W = null;
				_RComment_W = null;
				_IsActive_W = null;
				_DCreatedDate_W = null;
				_DModifiedDate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblRegistersInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.PkRegisterID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblRegistersUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblRegistersDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.PkRegisterID);
			p.SourceColumn = ColumnNames.PkRegisterID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.PkRegisterID);
			p.SourceColumn = ColumnNames.PkRegisterID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RName);
			p.SourceColumn = ColumnNames.RName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RDescription);
			p.SourceColumn = ColumnNames.RDescription;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FkVatID);
			p.SourceColumn = ColumnNames.FkVatID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RComment);
			p.SourceColumn = ColumnNames.RComment;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsActive);
			p.SourceColumn = ColumnNames.IsActive;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DCreatedDate);
			p.SourceColumn = ColumnNames.DCreatedDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DModifiedDate);
			p.SourceColumn = ColumnNames.DModifiedDate;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
